# Generated by Django 5.2.5 on 2025-08-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mitsuback", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="register",
            old_name="employee_id",
            new_name="company_name",
        ),
        migrations.RemoveField(
            model_name="register",
            name="email",
        ),
    ]
